immune:
    dir_screen: "data/processed/immune"
    plates: ["010"]
    markers:
        ch_01_neighbors: "DAPI"
        ch_02_neighbors: "COL1"
        ch_03_neighbors: "immune"
        ch_04_neighbors: "CK19"
        ch_01_nuclei: "DAPI"
        ch_02_nuclei: "COL1"
        ch_03_nuclei: "immune"
        ch_04_nuclei: "CK19"
    registered: false
    input_type: TIF_OVR_BG
    phenocoder:
        dir_models: "data/processed/immune/phenocoder"
        models:
            source:
                cycle: "01"
                file: "1st_cycle_nuclei/models/cond_latent_32_dense_64_dropout_0.25_beta_0.01_20241029-151845"
        n_comps_pca:
            nuclei: 6
            nuclei_msg: 4
            phenocoder: 32
            phenocoder_msg: 32
            org_embedding: 32
        cluster_res:
            nuclei: 0.2
            nuclei_msg: 0.2
            phenocoder: 0.5
            phenocoder_msg: 0.5
            org_embedding: 0.5

pilotscreen:
    dir_screen: "data/processed/pilotscreen"
    registered: true
    plates: ["004", "005"]
    input_type: TIF_OVR_BG
    qc:
        run: true
        qc_distance_threshold: 100
        qc_score_threshold: 3
    markers:
        source_ch_01_neighbors: "DAPI-1"
        source_ch_02_neighbors: "SDC1"
        source_ch_03_neighbors: "ITGA2"
        source_ch_04_neighbors: "LAMC2"
        target_ch_01_neighbors: "DAPI-2"
        target_ch_02_neighbors: "COL1"
        target_ch_03_neighbors: "KI67"
        target_ch_04_neighbors: "CK19"
        source_ch_01_nuclei: "DAPI-1"
        source_ch_02_nuclei: "SDC1"
        source_ch_03_nuclei: "ITGA2"
        source_ch_04_nuclei: "LAMC2"
        target_ch_01_nuclei: "DAPI-2"
        target_ch_02_nuclei: "COL1"
        target_ch_03_nuclei: "KI67"
        target_ch_04_nuclei: "CK19"
    phenocoder:
        dir_models: "data/processed/pilotscreen/phenocoder"
        models:
            source:
                cycle: "01"
                file: "1st_cycle_nuclei/models/cond_latent_32_dense_64_dropout_0.25_beta_0.01_20241030-000353"
            target:
                cycle: "03"
                file: "2nd_cycle_nuclei/models/cond_latent_32_dense_64_dropout_0.25_beta_0.01_20241029-230904"
        n_comps_pca:
            nuclei: 6
            nuclei_msg: 4
            phenocoder: 32
            phenocoder_msg: 32
            org_embedding: 32
        cluster_res:
            nuclei: 0.2
            nuclei_msg: 0.2
            phenocoder: 0.5
            phenocoder_msg: 0.5
            org_embedding: 0.5

tumoroidscreen:
    dir_screen: "data/processed/tumoroidscreen"
    plates: ["HM001", "HM002", "HM003", "HM004", "HM005", "HM006"]
    input_type: TIF_OVR_BG
    registered: true
    qc:
        run: true
        qc_distance_threshold: 300
        qc_score_threshold: 3
    markers:
        source_ch_01_neighbors: "DAPI-1"
        source_ch_02_neighbors: "SDC1"
        source_ch_03_neighbors: "ITGA2"
        source_ch_04_neighbors: "LAMC2"
        target_ch_01_neighbors: "DAPI-2"
        target_ch_02_neighbors: "COL1"
        target_ch_03_neighbors: "KI67"
        target_ch_04_neighbors: "CK19"
        source_ch_01_nuclei: "DAPI-1"
        source_ch_02_nuclei: "SDC1"
        source_ch_03_nuclei: "ITGA2"
        source_ch_04_nuclei: "LAMC2"
        target_ch_01_nuclei: "DAPI-2"
        target_ch_02_nuclei: "COL1"
        target_ch_03_nuclei: "KI67"
        target_ch_04_nuclei: "CK19"
    phenocoder:
        dir_models: "data/processed/tumoroidscreen/phenocoder"
        models:
            source:
                cycle: "01"
                file: "1st_cycle_nuclei/models/cond_latent_32_dense_64_dropout_0.25_beta_0.01_20241107-193606"
            target:
                cycle: "03"
                file: "2nd_cycle_nuclei/models/cond_latent_32_dense_64_dropout_0.25_beta_0.01_20241108-125516"
        n_comps_pca:
            nuclei: 6
            nuclei_msg: 4
            phenocoder: 32
            phenocoder_msg: 32
            org_embedding: 32
        cluster_res:
            nuclei: 0.2
            nuclei_msg: 0.2
            phenocoder: 0.5
            phenocoder_msg: 0.5
            org_embedding: 0.5

timecourse:
    dir_screen: "data/processed/timecourse"
    plates: ["001", "002", "003", "004", "005"]
    input_type: TIF_OVR_BG
    registered: false
    markers:
        ch_01_neighbors: "DAPI"
        ch_01_nuclei: "DAPI"
    phenocoder:
        dir_models: data/processed/timecourse/phenocoder
        models:
            source:
                cycle: "01"
                file: "models/cond_latent_64_dense_128_dropout_0.25_beta_0.01_20250707-160431"
        n_comps_pca:
            nuclei: 6
            nuclei_msg: 4
            phenocoder: 32
            phenocoder_msg: 32
            org_embedding: 32
            imputed_neighbors_bytimepoints_False: 18
            imputed_nuclei_bytimepoints_False: 18
        cluster_res:
            nuclei: 0.2
            nuclei_msg: 0.2
            phenocoder: 0.5
            phenocoder_msg: 0.5
            org_embedding: 0.5
            imputed_neighbors_bytimepoints_False: 0.7
            imputed_nuclei_bytimepoints_False: 0.7

pilotscreen_noplatecondition:
    dir_screen: "data/pilotscreen"
    registered: true
    plates: ["004", "005"]
    input_type: TIF_OVR_BG
    qc:
        run: true
        qc_distance_threshold: 100
        qc_score_threshold: 3
    markers:
        source_ch_01_neighbors: "DAPI-1"
        source_ch_02_neighbors: "SDC1"
        source_ch_03_neighbors: "ITGA2"
        source_ch_04_neighbors: "LAMC2"
        target_ch_01_neighbors: "DAPI-2"
        target_ch_02_neighbors: "COL1"
        target_ch_03_neighbors: "KI67"
        target_ch_04_neighbors: "CK19"
        source_ch_01_nuclei: "DAPI-1"
        source_ch_02_nuclei: "SDC1"
        source_ch_03_nuclei: "ITGA2"
        source_ch_04_nuclei: "LAMC2"
        target_ch_01_nuclei: "DAPI-2"
        target_ch_02_nuclei: "COL1"
        target_ch_03_nuclei: "KI67"
        target_ch_04_nuclei: "CK19"
    phenocoder:
        dir_models: "data/pilotscreen/phenocoder"
        models:
            source:
                cycle: "01"
                file: "1st_cycle_nuclei/models/cond_latent_32_dense_64_dropout_0.25_beta_0.01_20260317-135744"
            target:
                cycle: "03"
                file: "2nd_cycle_nuclei/models/cond_latent_32_dense_64_dropout_0.25_beta_0.01_20260317-185029"
        n_comps_pca:
            nuclei: 6
            nuclei_msg: 4
            phenocoder: 32
            phenocoder_msg: 32
            org_embedding: 32
        cluster_res:
            nuclei: 0.2
            nuclei_msg: 0.2
            phenocoder: 0.5
            phenocoder_msg: 0.5
            org_embedding: 0.5
